#!/bin/bash

echo "setting up user: $1 (password: $2)..."
useradd -m -p `perl -e "print(crypt('$2', 'a9'));"` -s /bin/bash $1
chsh -s /bin/zsh $1
if [ "$3" = "1" ]; then
    echo "add sudo to user..."
    usermod -aG sudo $1;
fi

echo "setting xrdp..."
cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
sed -i 's/max_bpp=32/#max_bpp=32\nmax_bpp=128/g' /etc/xrdp/xrdp.ini
sed -i 's/xserverbpp=24/#xserverbpp=24\nxserverbpp=128/g' /etc/xrdp/xrdp.ini

echo "setting user..."
su - $1 -c "wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -e"
su - $1 -c "cp /usr/local/share/.zshrc ./"
su - $1 -c "echo 'wmaker' > .xsession"

echo "running dbus and xrdp daemon..."
service dbus start
service xrdp start

echo "running pulseaudio..."
su - $1 -c "pulseaudio -D"

echo "running sshd daemon..."
/usr/sbin/sshd -D